export interface FeedStory { id: string; title: string; link: string; publishedAt: string; description: string; }
export const feedCache: Record<string, FeedStory[]> = {
  'nc-political-news': [
    { id: 'todays-nc-political-news-briefs-4-wbkxr', title: 'Today’s NC Political News briefs', link: 'https://www.ncpoliticalnews.com/news/todays-nc-political-news-briefs-4-wbkxr', publishedAt: 'Wed, 16 Sep 2026 10:32:07 +0000', description: 'North Carolina boards and agencies prepare for election-rule review, education grants, a coastal regulatory decision and a State Board of Community Colleges meeting.' },
    { id: '988-behavioral-health', title: 'North Carolina receives nearly $7 million for 988 and behavioral-health services', link: 'https://www.ncpoliticalnews.com/news/north-carolina-receives-nearly-7-million-for-988-and-behavioral-health-services', publishedAt: 'Wed, 16 Sep 2026 10:31:25 +0000', description: 'Three federal grants totaling approximately $7 million will support North Carolina’s 988 crisis line, mobile crisis teams and maternal substance-use treatment.' },
    { id: 'stein-film-incentive', title: 'Stein calls for legislative solution to give North Carolina film incentive greater certainty', link: 'https://www.ncpoliticalnews.com/news/stein-calls-for-legislative-solution-to-give-north-carolina-film-incentive-greater-certainty', publishedAt: 'Wed, 16 Sep 2026 10:30:43 +0000', description: 'Gov. Josh Stein says his administration wants to work with legislators to provide greater certainty for North Carolina’s publicly funded film-production incentive.' },
    { id: 'nc-college-connect', title: 'NC College Connect expands direct admission to every graduating public school senior', link: 'https://www.ncpoliticalnews.com/news/nc-college-connect-expands-direct-admission-to-every-graduating-public-school-senior', publishedAt: 'Wed, 16 Sep 2026 10:29:47 +0000', description: 'More than 105,000 North Carolina public school seniors will receive at least one direct college admission offer under an expansion of NC College Connect.' },
    { id: 'briefs-sept-15', title: 'Today’s NC Political News briefs', link: 'https://www.ncpoliticalnews.com/news/todays-nc-political-news-briefs-4', publishedAt: 'Tue, 15 Sep 2026 10:44:25 +0000', description: 'State officials are preparing for an election-board meeting while directing new funding toward education assessments and rural school health services.' },
    { id: 'mental-health-settlement', title: 'North Carolina seeks end to court oversight of mental-health settlement', link: 'https://www.ncpoliticalnews.com/news/north-carolina-seeks-end-to-court-oversight-of-mental-health-settlement', publishedAt: 'Tue, 15 Sep 2026 10:43:34 +0000', description: 'North Carolina and the U.S. Department of Justice have asked a federal court to end oversight of a 2012 community mental-health settlement.' },
    { id: 'party-sales-rule', title: 'State opens comment on political-party sales rule', link: 'https://www.ncpoliticalnews.com/news/state-opens-comment-on-political-party-sales-rule', publishedAt: 'Tue, 15 Sep 2026 10:39:18 +0000', description: 'North Carolina has opened public comment on filing and disclosure requirements for political-party exempt sales plans.' },
    { id: 'atrium-state-health', title: 'Atrium agreement expands State Health Plan access for 2027', link: 'https://www.ncpoliticalnews.com/news/atrium-agreement-expands-state-health-plan-access-for-2027', publishedAt: 'Tue, 15 Sep 2026 10:38:22 +0000', description: 'Twelve Atrium Health hospitals and associated clinics will enter the State Health Plan’s Access tier beginning Jan. 1.' },
    { id: 'jackson-data-centers', title: 'Jackson proposes separate utility rate class for data centers', link: 'https://www.ncpoliticalnews.com/news/jackson-proposes-separate-utility-rate-class-for-data-centers', publishedAt: 'Tue, 15 Sep 2026 10:36:31 +0000', description: 'Attorney General Jeff Jackson is asking state regulators to create a separate utility rate class for data centers and other large electricity users.' },
    { id: 'tillis-crypto', title: 'Tillis helps secure stronger ethics provisions in federal cryptocurrency bill', link: 'https://www.ncpoliticalnews.com/news/tillis-helps-secure-stronger-ethics-provisions-in-federal-cryptocurrency-bill', publishedAt: 'Mon, 14 Sep 2026 10:46:05 +0000', description: 'North Carolina Sen. Thom Tillis helped negotiate ethics provisions giving state attorneys general a role in enforcing proposed federal cryptocurrency restrictions.' }
  ]
};
