import { useMemo, useState, type CSSProperties } from 'react';
import { starterBrands } from './seed';
import { feedCache, type FeedStory } from './feed-cache';
import type { Brand } from './types';
import './story-desk.css';
import './storyboard-builder.css';
import './local-studio.css';

type Scene = { label: string; voiceover: string; visualText: string; animation: string; approved: boolean; kind: 'image' | 'fact' };
type Activity = { when: string; person: string; action: string };
const actors = ['Kristy Kelly', 'BJ Murphy'];
const animations = ['Slow editorial drift', 'Diagonal sweep', 'Card rise', 'Soft pulse'];
const appeals: Scene[] = [
  { label: 'Power shift upheld', voiceover: 'North Carolina’s Appeals Court has upheld the law shifting elections-board appointment power to State Auditor Dave Boliek.', visualText: 'Auditor keeps elections-board appointment power.', animation: 'Slow editorial drift', approved: false, kind: 'image' },
  { label: 'What changed', voiceover: 'The ruling leaves Boliek in control of appointments to the State Board of Elections and all 100 county boards.', visualText: 'State board + all 100 county boards', animation: 'Card rise', approved: false, kind: 'fact' },
  { label: 'The ruling', voiceover: 'The court ruled 2 to 1, reversing an earlier decision that found the law unconstitutional.', visualText: 'Appeals Court rules 2–1', animation: 'Diagonal sweep', approved: false, kind: 'fact' },
  { label: 'Why it matters', voiceover: 'The ruling has already shifted the State Board and county boards to Republican majorities.', visualText: 'Board control has shifted statewide.', animation: 'Soft pulse', approved: false, kind: 'fact' },
  { label: 'What happens next', voiceover: 'The court said future power-transfer disputes must be decided case by case.', visualText: 'Future cases will be judged individually.', animation: 'Card rise', approved: false, kind: 'fact' },
];

function localRead<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || '') as T; } catch { return fallback; } }
function localWrite(key: string, value: unknown) { localStorage.setItem(key, JSON.stringify(value)); }

export function LocalStudio() {
  const [person, setPerson] = useState(() => localStorage.getItem('lve-local-person') || actors[0]);
  const [brandId, setBrandId] = useState('nc-political-news');
  const [story, setStory] = useState<FeedStory | null>(null);
  const [packages, setPackages] = useState(() => localRead<{ headline: string; status: string; by: string }[]>('lve-local-packages', []));
  const [activity, setActivity] = useState(() => localRead<Activity[]>('lve-local-activity', []));
  const brand = starterBrands.find(item => item.id === brandId) || starterBrands[0];
  const stories = feedCache[brand.id] || [];
  const note = (action: string) => { const next = [{ when: new Date().toLocaleString(), person, action }, ...activity].slice(0, 25); setActivity(next); localWrite('lve-local-activity', next); };
  const start = (item: FeedStory) => { setStory(item); note(`opened “${item.title}”`); };
  if (story) return <LocalStoryboard brand={brand} story={story} person={person} onClose={() => setStory(null)} onActivity={note} onPackage={(item) => { const next = [item, ...packages]; setPackages(next); localWrite('lve-local-packages', next); }} />;
  return <main className="shell" style={{ '--brand': brand.colors.primary, '--accent': brand.colors.accent } as CSSProperties}><aside><div className="mark"><span>MM</span><strong>Local Voice<br/>Engine</strong></div><nav><button className="selected">Studio</button><button>Library</button><button>Templates</button><button>Activity</button></nav><div className="profile"><b>Local studio</b><small>No cloud services connected</small><label className="local-person">Working as<select value={person} onChange={event => { setPerson(event.target.value); localStorage.setItem('lve-local-person', event.target.value); }}><option>Kristy Kelly</option><option>BJ Murphy</option></select></label></div></aside><section className="content"><header><div><p className="eyebrow">{brand.name}</p><h1>Story desk</h1></div><span className="local-badge">Local-only workspace</span></header><div className="brand-rail">{starterBrands.map(item => <button key={item.id} onClick={() => setBrandId(item.id)} className={item.id === brand.id ? 'brand active' : 'brand'} style={{ '--chip': item.colors.primary } as CSSProperties}>{item.name}</button>)}</div><section className="story-desk"><div className="story-desk-head"><div><p className="eyebrow">Saved reporting</p><h2>Choose a story to make a video.</h2></div><span className="local-note">RSS refresh is available from the local engine.</span></div>{stories.length ? <div className="story-list">{stories.slice(0, 10).map((item, index) => <button className="story-row" key={item.id} onClick={() => start(item)}><b>{String(index + 1).padStart(2, '0')}</b><div><h3>{item.title}</h3><p>{item.description}</p><small>{new Date(item.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} · {brand.name}</small></div><i>Make video →</i></button>)}</div> : <div className="empty-feed"><h2>This brand’s local feed is ready to connect.</h2><p>Its visual kit is already included in the studio.</p></div>}</section><section className="section-head"><div><p className="eyebrow">Local activity</p><h2>Packages and work log</h2></div></section><section className="cards">{packages.length ? packages.slice(0, 3).map((item, index) => <article key={`${item.headline}-${index}`}><div className="card-art"/><p>{item.status}</p><h3>{item.headline}</h3><small>{item.by}</small></article>) : <article className="empty"><span>✦</span><h3>No local packages yet.</h3><p>Choose a saved story above to begin.</p></article>}<article className="activity-card"><p>Recent activity</p>{activity.slice(0, 3).map((item, index) => <small key={index}><b>{item.person}</b> {item.action}<br/>{item.when}</small>)}</article></section></section></main>;
}

function LocalStoryboard({ brand, story, person, onClose, onActivity, onPackage }: { brand: Brand; story: FeedStory; person: string; onClose: () => void; onActivity: (text: string) => void; onPackage: (item: { headline: string; status: string; by: string }) => void }) {
  const initial = useMemo(() => story.id === 'appeals-court-election-power' ? appeals : [{ label: 'Story opener', voiceover: story.description, visualText: story.title, animation: 'Slow editorial drift', approved: false, kind: 'image' as const }], [story]);
  const [scenes, setScenes] = useState(initial); const [active, setActive] = useState(0); const [notice, setNotice] = useState(''); const scene = scenes[active];
  const change = (key: keyof Scene, value: string | boolean) => setScenes(current => current.map((item, index) => index === active ? { ...item, [key]: value } : item));
  const approve = () => { change('approved', true); onActivity(`approved Scene ${active + 1} of “${story.title}”`); setNotice(`Scene ${active + 1} approved locally.`); };
  const compile = () => { if (!scenes.every(item => item.approved)) return setNotice('Approve every scene before sending it to the local renderer.'); onPackage({ headline: story.title, status: 'ready for local render', by: person }); onActivity(`prepared “${story.title}” for the local renderer`); setNotice('Storyboard is ready for the local Qwen render worker.'); };
  return <main className="storyboard-builder" style={{ '--brand': brand.colors.primary, '--accent': brand.colors.accent } as CSSProperties}><header className="builder-bar"><button onClick={onClose}>← Story desk</button><div><p>{brand.name} · local storyboard</p><strong>{story.title}</strong></div><span>Working as {person}</span></header><main className="storyboard-workspace"><aside className="scene-nav"><p className="eyebrow">Storyboard</p>{scenes.map((item, index) => <button key={index} onClick={() => { setActive(index); setNotice(''); }} className={active === index ? 'active' : ''}><span>Scene {index + 1}</span><strong>{item.label}</strong><i>{item.approved ? 'Approved' : 'Needs review'}</i></button>)}<button className="compile" onClick={compile}>Send to local renderer →</button>{notice && <p className="notice">{notice}</p>}</aside><section className="scene-editor"><p className="eyebrow">Scene {active + 1} of {scenes.length}</p><label>Label<input value={scene.label} onChange={event => change('label', event.target.value)} /></label><label>Voiceover text<textarea value={scene.voiceover} onChange={event => change('voiceover', event.target.value)} /></label><p className="local-render-note">Voice generation stays on this Mac. The local Qwen renderer will be connected here next.</p><label>Visual text<input value={scene.visualText} onChange={event => change('visualText', event.target.value)} /></label><label>Background animation<select value={scene.animation} onChange={event => change('animation', event.target.value)}>{animations.map(item => <option key={item}>{item}</option>)}</select></label><button className="approve" onClick={approve}>{scene.approved ? '✓ Scene approved' : 'Approve this scene'}</button></section><section className={`scene-preview animation-${scene.animation.toLowerCase().replaceAll(' ', '-')}`}><p className="eyebrow">Live scene preview</p><div className={`reel-scene ${scene.kind}`}><div className="scene-brand">{brand.logoUrl ? <img src={brand.logoUrl} alt={brand.name} /> : brand.name}</div><h2>{scene.label}</h2>{scene.kind === 'image' ? <div className="scene-photo">{story.imageUrl && <img src={story.imageUrl} alt="Article lead" />}</div> : <div className="scene-fact"><span>{scene.label}</span><strong>{scene.visualText}</strong></div>}<p className="scene-visual">{scene.visualText}</p><small>Read the full story at {brand.site?.replace(/^https?:\/\//, '')}</small></div><p className="preview-note">This screen is fully local. Every edit and approval is logged to this Mac.</p></section></main></main>;
}
